config/routes.rb
Rails.application.routes.draw do

  root "sessions#index"
  post "/sessions" => "sessions#create", as: "new_session"
  get "/sessions" => "sessions#index", as: "sessions"
  get "/logout" => "sessions#index", as: "logout"
  delete "/logout" => "sessions#destroy", as: "signout"

  resources :users

  resources :details, except: [:index, :show, :destroy]
  resources :additionals, except: [:index, :show, :destroy]
  resources :accounts, except: [:index, :show, :destroy]

  resources :percentages, only: [:edit, :update]
  resources :payslips, only: [:create, :show]
  get '/payslips/:id/all' => "payslips#index", as: "all_payslips"
  get '/payslips/new/:id' => "payslips#new", as: "new_payslip"
  get "payslips" => "users#index"
  delete '/delete/payslip/:id' => "payslips#destroy", as: "delete_payslip"
end

app/models/payslip.rb
class Payslip < ApplicationRecord
  validates_uniqueness_of :pay_id
end

app/controllers/payslips_controller.rb
class PayslipsController < ApplicationController
  layout "payslip", only: [:show]

  def index
    @payslips = Payslip.select(:id,:pay_id,:month,:year, :net).where(user_id: params[:id])
    @detail = Detail.find_by(user_id: params[:id])
  end

  def new
    @payslip = Payslip.new
    @detail = Detail.find_by(user_id: params[:id])
    session[:id] = @detail.id
  end

  def create
    @error
    @payslip = Payslip.new(pay_params)
    @detail = Detail.find(session[:id])
    @per = Percentage.find(1)
    @payslip.user_id = @detail.user_id
    @payslip.pay_id = @detail.empid << @payslip.month.to_s.rjust(2,"0") << @payslip.year.to_s
    @payslip.basic = (@payslip.gross / (1+(@per.hra_per/100)+(@per.cca_per/100)+(@per.spl_all_per/100)+(@per.trans_all_per/100))).to_i
    @payslip.hra = (@payslip.basic * (@per.hra_per/100)).to_i
    @payslip.cca = (@payslip.basic * (@per.cca_per/100)).to_i
    @payslip.spl_all = (@payslip.basic * (@per.spl_all_per/100)).to_i
    @payslip.trans_all = (@payslip.basic * (@per.trans_all_per/100)).to_i
    @payslip.lop = ((@payslip.gross/30)*@payslip.days).to_i
    @payslip.p_tax = find_ptax(@payslip.gross)
    @payslip.gross = @payslip.gross+@payslip.reimb
    @payslip.net = (@payslip.gross - (@payslip.lop+@payslip.deduction+@payslip.p_tax)).to_i
    @payslip.basic = @payslip.basic + (@payslip.gross-(@payslip.basic+@payslip.hra+@payslip.cca+@payslip.spl_all+@payslip.trans_all))
    @payslip.ctc = @payslip.gross*12
    @payslip.no_days = find_days(@payslip.month,@payslip.year)
    if @payslip.year == (@detail.doj.strftime("%Y").to_i)
      if @payslip.month >= (@detail.doj.strftime("%m").to_i)
        if @payslip.save
          redirect_to payslip_path(@payslip)
        else
          @error = "Payslip already created"
          render "new"
        end
      else
        @error = "Month should be within Date of Joining"
        render "new"
      end
    else
      if @payslip.save
        redirect_to payslip_path(@payslip)
      else
        @error = "Payslip already created"
        render "new"
      end
    end
  end

  def show
    @payslip = Payslip.find(params[:id])
    @detail = Detail.find_by(user_id: @payslip.user_id)
    @account = Account.find_by(user_id: @payslip.user_id)
    @temp = @payslip.month.to_i.humanize
		dict = {"one" => "January", "two" => "Febraury", "three" => "March", "four" => "April", "five" => "May", "six" => "June", "seven" => "July", "eight" => "August", "nine" => "September", "ten" => "October", "eleven" => "November", "twelve" => "December"}
		@temp = dict[@temp]
    respond_to do |format|
      format.html
      format.pdf do
        pdf = PayslipPdf.new(@payslip,@temp)
        send_data pdf.render, filename: "payslip_#{@payslip.id}.pdf", type: "application/pdf"
      end
    end
  end

  def destroy
    @payslip = Payslip.find(params[:id])
    @user = User.find(@payslip.user_id)
    @payslip.delete
    redirect_to all_payslips_path(@user)
  end

  private

  def pay_params
    params.require(:payslip).permit(:pay_id,:user_id,:basic,:hra,:cca,:spl_all,:trans_all,:reimb,:lop,:deduction,:p_tax,:gross,:net,:ctc,:days,:month,:year)
  end

  def find_ptax(gross)
    if gross>=15000
      200
    else
      0
    end
  end

  def find_days(month,year)
    t31 = [1,3,5,7,8,10,12]
    t30 = [4,6,9,11]
    if t31.include?(month)
      31
    elsif t30.include?(month)
      30
    else
      if year%4==0 && year%100==0 && year%400==0
        29
      else
        28
      end
    end
  end
end

app/helpers/payslips_helper.rb
module PayslipsHelper
end

app/views/payslips/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="font-bebas" style="color:white;">
      PAY SLIPS - <%= @detail.empid %>
    </div>
    <table class="table table-striped table-dark">
      <tr>
        <th>Pay ID</th>
        <th>Month/Year</th>
        <th>Net Salary</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
        <%= @payslips.each do |pay|%>
          <tr>
            <td><%= pay.pay_id %></td>
            <td><%= pay.month.to_s.rjust(2,"0")%> - <%= pay.year%></td>
            <td><%= pay.net %></td>
            <td style="width:10%;text-align:center;"><%= link_to "View", payslip_path(pay), :target => "_blank" %></td>
            <td style="width:10%;text-align:center;"><%= link_to 'Download', "/payslips/"<<pay.id.to_s<<".pdf", :target => '_blank' %></td>
            <td style="width:10%;text-align:center;"><%= link_to "Delete", delete_payslip_path(pay), method: :delete, data: {confirm: "Are you sure?"} %></td>
          </tr>
        <% end %>
    </table>
    <%= @payslips.each do%>
      <pre>

      </pre>
    <% end %>
  </body>
</html>

app/views/payslips/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="font-bebas" style="color:white;">
      GENERATE PAYSLIP
    </div>
    <%= form_for @payslip do |f|%>
        <table class="table table-striped table-dark">
          <div class="font-beba-small">
          <tr>
            <td><%= f.label "Employee Name"%></td>
            <td><%= @detail.fname%></td>
            <td><%= f.label "Employee ID"%></td>
            <td><%= @detail.empid%></td>
          </tr>
          <tr>
            <td><%= f.label "Date of Joining"%></td>
            <td><%= @detail.doj%></td>
            <td colspan="2"></td>
          </tr>
          <tr>
            <td><%= f.label "Generate for"%></td>
            <td><%= f.select :month, [['MONTH',0],['JANUARY',1],['FEBRUARY',2],['MARCH',3],['APRIL',4],['MAY',5],['JUNE',6],['JULY',7],['AUGUST',8],['SEPTEMBER',9],
              ['OCTOBER',10],['NOVEMBER',11],['DECEMBER',12]]%></td>
            <td><%= f.label "Year"%></td>
            <td><%= f.number_field :year, :min=>(@detail.doj.strftime("%Y").to_i), :max=>(Time.now.strftime("%Y").to_i)%></td>
          </tr>
          <tr>
            <td><%= f.label "Gross Salary"%></td>
            <td><%= f.number_field :gross, :min=>0%></td>
            <td><%= f.label "Reimbursments"%></td>
            <td><%= f.number_field :reimb, :min=>0%></td>
          </tr>
          <tr>
            <td><%= f.label "Number of leaves in days"%></td>
            <td><%= f.number_field :days, :min=>0%></td>
            <td><%= f.label "Other Deductions"%></td>
            <td><%= f.number_field :deduction, :min=>0%></td>
          </tr>
          <tr>
            <td><%= f.submit "Update"%></td>
            <td colspan="3"><span><font color="red"><%= @error %></font></span></td>
          </tr>
        </table>
    <% end %>
    <pre>













    </pre>
  </body>
</html>

app/views/payslips/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

  </head>
  <body>
      <%= link_to 'Back', all_payslips_path(@payslip.user_id) %>&nbsp;&nbsp;&nbsp;&nbsp;
      <%= link_to 'Download Payslip', "/payslips/"<<@payslip.id.to_s<<".pdf", :target => '_blank' %>
      <fieldset>
        <table>
          <tr>
            <td colspan="4"><img src="http://www.exalogic.in/wp-content/uploads/2018/08/exalogic.png" height="60" alt="Exalogic"></td>
          </tr>
          <tr>
            <td colspan="4" height="7"></td>
          </tr>
          <tr>
            <td colspan="4" style="text-align:center;">Exalogic Solutions Pvt Ltd</td>
          </tr>
          <tr>
            <td colspan="4" style="text-align:center;">22, Ganganagar, 1st Main Road, Bangalore - 560032, India</td>
          </tr>
          <tr>
            <td colspan="4" height="10"></td>
          </tr>
          <tr>
            <td colspan="4"><hr></td>
          </tr>
          <tr>
            <td colspan="4"><div class="font-bebas" style="color:black;font-size:30px;">
              <%= @temp %> - <%= @payslip.year %> - PAYSLIP
            </div></td>
          </tr>
          <tr>
            <td colspan="4"><hr></td>
          </tr>
          <tr>
            <td><strong>Employee ID</strong></td><td><%= @detail.empid %></td>
            <td><strong>Name</strong></td><td><%= @detail.fname %></td>
          </tr>
          <tr>
            <td><strong>Department</strong></td><td><%= @detail.department %></td>
            <td><strong>Designation</strong></td><td><%= @detail.designation %></td>
          </tr>
          <tr>
            <td><strong>Date of Joining</strong></td><td><%= @detail.doj %></td>
            <td><strong>No of Days in the month</strong></td><td><%= @payslip.no_days %></td>
          </tr>
          <tr>
            <td><strong>Bank Account</strong></td><td><%= @account.accno %></td>
            <td><strong>Bank Name</strong></td><td><%= @account.bank %>, <%= @account.branch %></td>
          </tr>
          <tr>
            <td colspan="4" height="15"></td>
          </tr>
          <table style="border:1px solid black;text-align:center;">
            <tr>
              <th>Earnings</th>
              <th>Amount</th>
              <th>Deductions</th>
              <th>Amount</th>
            </tr>
            <tr>
              <td colspan="4"><hr></td>
            </tr>
            <tr>
              <td>Basic Pay</td><td><%= @payslip.basic.to_i %></td>
              <td>Professional Tax</td><td><%= @payslip.p_tax.to_i %></td>
            </tr>
            <tr>
              <td>HRA</td><td><%= @payslip.hra.to_i %></td>
              <td>Loss of Pay</td><td><%= @payslip.lop.to_i %></td>
            </tr>
            <tr>
              <td>CCA</td><td><%= @payslip.cca.to_i %></td>
              <td>Deductions</td><td><%= @payslip.deduction.to_i %></td>
            </tr>
            <tr>
              <td>Special Allowance</td><td><%= @payslip.spl_all.to_i %></td>
              <td></td><td></td>
            </tr>
            <tr>
              <td>Transport Allowance</td><td><%= @payslip.trans_all.to_i %></td>
              <td></td><td></td>
            </tr>
            <tr>
              <td>Reimbursments</td><td><%= @payslip.reimb.to_i %></td>
              <td></td><td></td>
            </tr>
            <tr>
              <td colspan="4"><hr></td>
            </tr>
            <tr>
              <th>Total Earnings</th><td><%= @payslip.gross.to_i %></td>
              <th>Total Deductions</th><td><%= (@payslip.lop+@payslip.p_tax+@payslip.deduction).to_i %></td>
            </tr>
            <tr>
              <td colspan="4"><hr></td>
            </tr>
            <tr>
              <td colspan="2"></td>
              <th>Net Pay</th><td><%= @payslip.net %></td>
            </tr>
          </table>
          <tr>
            <td colspan="4"><br></td>
          </tr>
          <tr>
            <td><strong>Net Pay</strong> (in words) : </td>
          </tr>
          <tr>
            <td colspan="2"> <%= @payslip.net.humanize.capitalize << " rupees only" %></td>
          </tr>
          <tr>
            <td colspan="4"><hr></td>
          </tr>
          <tr>
            <td colspan="4"><p style="text-align:center;">***This is a system generated payslip and does not require signature</p></td>
          </tr>
          <tr><td></td>
          </tr>
        </table>
      </fieldset>
  </body>
</html>