config/routes.rb
Rails.application.routes.draw do

  root "sessions#index"
  post "/sessions" => "sessions#create", as: "new_session"
  get "/sessions" => "sessions#index", as: "sessions"
  get "/logout" => "sessions#index", as: "logout"
  delete "/logout" => "sessions#destroy", as: "signout"

  resources :users

  resources :details, except: [:index, :show, :destroy]
  resources :additionals, except: [:index, :show, :destroy]
  resources :accounts, except: [:index, :show, :destroy]

  resources :percentages, only: [:edit, :update]
  resources :payslips, only: [:create, :show]
  get '/payslips/:id/all' => "payslips#index", as: "all_payslips"
  get '/payslips/new/:id' => "payslips#new", as: "new_payslip"
  get "payslips" => "users#index"
  delete '/delete/payslip/:id' => "payslips#destroy", as: "delete_payslip"
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_one :detail
  validates_uniqueness_of :email
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_admin?, except: [:show]
  before_action :is_user?, only: [:show]
  before_action :find_user, except: [:index, :new, :create]

  def index
    @details = Detail.all
    @users = User.all
    @count = count_users(@users)
  end

  def new
    @user = User.new
    session[:temp] = nil
  end

  def create
    @error
    @user = User.new(user_params)
    if @user.role == 'admin' && @user.save
      redirect_to users_path
    elsif @user.role == 'user' && @user.save
      session[:id] = @user.id
      redirect_to new_detail_path
    else
      @error = "Passwords are not matching"
      render "new"
    end
  end

  def show
    @detail = Detail.find_by(user_id: @user.id)
    @additional = Additional.find_by(user_id: @user.id)
    @account = Account.find_by(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
    session[:id] = @user.id
    session[:temp]='edit'
  end

  def update
    @user = User.find(params[:id])
    @error
    if @user.update(user_params)
      redirect_to edit_detail_path(@user)
    else
      @error = "Please fill all the mandatory fields"
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    Detail.find_by(user_id: user.id).delete
    Additional.find_by(user_id: user.id).delete
    Account.find_by(user_id: user.id).delete
    Payslip.where(user_id: user.id).destroy_all
    user.delete
    redirect_to '/users'
  end

  private

  def is_user?
    unless session[:user_type] != nil || session[:user_id] == params[:id]
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)
  end

  def find_user
    @user = User.find(params[:id])
  end

  def count_users(users)
      count = 0
      users.each do |user|
        unless user.role=='admin'
          count+=1
        end
      end
      count
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f|%>
<span><%= @create_error%></span>
<table class="table table-striped table-dark">
    <tr>
      <td class=" active-tab" style="vertical-align:middle;"><label>Login Details</label></td>
      <td class="" style="vertical-align:middle; color:grey;"><label>Personal Details</label></td>
      <td class="" style="vertical-align:middle; color:grey;"><label>Additional Details</label></td>
      <td class="" style="vertical-align:middle; color:grey;"><label>Account Details</label></td>
    </tr>
  <tr>
    <td><%= f.label "Email"%><font color="red"> *</font></td>
    <td><%= f.email_field :email, :required=>true%></td>
    <td><%= f.label "Role"%><font color="red"> *</font></td>
    <td><%= f.select :role, [['User','user'],['Admin','admin']] %><span><%= @user.errors[:role][0] rescue nil%></span></td>
  </tr>
  <tr>
    <td><%= f.label "Password"%></td>
    <td><%= f.password_field :password, :minlength => 6%></td>
    <td><%= f.label "Confirm Password"%></td>
    <td><%= f.password_field :password_confirmation, :minlength => 6%></td>
  </tr>
  <tr>
    <td><%= f.submit "Next"%></td>
    <td colspan="3"><span><%= @error %></span></td>
  </tr>
</table>
<pre>
</pre>
<% end%>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="font-bebas">
      EDIT USERS
    </div>
    <%= render "form" %>
    <pre>














    </pre>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container">
      <% i=0%>
                <table>
                  <tr>
                    <td></td>
                    <td align="center">
                      <div class="cont">
                      <div class="font-bebas" style="font-size:30px;">
                        <i class="fas fa-user-circle fa-3x"></i><br>
                        USERS COUNT<br>
                        <%= @count %>
                      </div>
                    </div>
                    </td>
                    <td></td>
                  </tr>
                  <tr>
                    <td colspan="3">
                      <div class="font-bebas" style="color:white;">
                        USERS
                      </div>
                    </td>
                  </tr>
                  <% @details.each do |detail|%>
                      <% user = User.find(detail.user_id) %>
                      <% if user.role != 'admin' %>
                      <% if i%3==0%>
                        <tr>
                          <td align="center">
                            <a href="<%= user_path(user)%>" style="text-decoration:none;">
                              <div class="card">
                                <% if detail.gender=='Male'%>
                                  <img src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar" style="width:100%">
                                <%else%>
                                  <img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Avatar" style="width:100%">
                                <% end%>
                                <div class="container-card">
                                  <h4 class="font-bebas" style="color:black; text-align:left;"><b><%= detail.fname%><br></b></h4>
                                  <p class="font-beba-small" style="color:grey; text-align:right;"><%= user.email%></p>
                                </div>
                              </div>
                            </a>

                          </td>
                      <% elsif i%3==1%>
                          <td align="center">
                            <a href="<%= user_path(user)%>" style="text-decoration:none;">
                              <div class="card">
                                <% if detail.gender=='Male'%>
                                  <img src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar" style="width:100%">
                                <%else%>
                                  <img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Avatar" style="width:100%">
                                <% end%>
                                <div class="container-card">
                                  <h4 class="font-bebas" style="color:black; text-align:left;"><b><%= detail.fname%><br></b></h4>
                                  <p class="font-beba-small" style="color:grey; text-align:right;"><%= user.email%></p>
                                </div>
                              </div>
                            </a>

                          </td>
                      <% else%>
                          <td align="center">
                            <a href="<%= user_path(user)%>" style="text-decoration:none;">
                              <div class="card">
                                <% if detail.gender=='Male'%>
                                  <img src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar" style="width:100%">
                                <%else%>
                                  <img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Avatar" style="width:100%">
                                <% end%>
                                <div class="container-card">
                                  <h4 class="font-bebas" style="color:black; text-align:left;"><b><%= detail.fname%><br></b></h4>
                                  <p class="font-beba-small" style="color:grey; text-align:right;"><%= user.email%></p>
                                </div>
                              </div>
                            </a>

                          </td>
                        </tr>
                      <% end%>
                      <% i+=1%>
                  <% end%>
                  <% end %>
                </table>
    </div>
    <% @users.each do |user|%>
        <pre>

        </pre>
    <% end%>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="font-bebas">
      CREATE USERS
    </div>
    <%= render "form" %>
    <pre>












    </pre>
  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <div class="container">
      <pre>
<div class="font-beba">
  <%= @detail.empid%></div><div class="font-beba-small">
  <table class="table table-striped table-dark">
            <tr>
              <td>First Name</td><td><%= @detail.fname%></td>
              <td>Last Name</td><td><%= @detail.lname%></td>
            </tr>
            <tr>
              <td>Date of Birth</td><td><%= @detail.dob%></td>
              <% if @detail.dob!=nil%>
                <td>Age</td><td><%= ((Date.today-@detail.dob.to_date)/365).to_i%></td>
              <% else%>
                <td>Age</td><td></td>
              <% end%>
            </tr>
            <tr>
              <td>Date of Joining</td><td><%= @detail.doj%></td>
              <td>Blood Group</td><td><%= @detail.bloodgroup%></td>
            </tr>
            <tr>
              <td>Contact</td><td><%= @detail.contact%></td>
              <td>Email</td><td><%= @user.email%></td>
            </tr>
            <tr>
              <td>Address</td><td><%= @detail.address%></td>
              <td>City</td><td><%= @detail.city%></td>
            </tr>
            <tr>
              <td>State</td><td><%= @detail.state%></td>
              <td>Country</td><td><%= @detail.country%></td>
            </tr>
            <tr>
              <td>Pincode</td><td><%= @detail.pincode%></td>
              <td>Notice period in days</td><td><%= @additional.notice%></td>
            </tr>
            <tr>
              <td>additional Contact Name</td><td><%= @additional.ename%></td>
              <td>Relation</td><td><%= @additional.relation%></td>
            </tr>
            <tr>
              <td>additional Contact Number</td><td><%= @additional.econtact%></td>
              <td>Gender</td><td><%= @detail.gender%></td>
            </tr>
            <tr>
              <td>Primary Skill</td><td><%= @additional.pskill%></td>
              <td>Secondary Skill 1</td><td><%= @additional.sskill1%></td>
            </tr>
            <tr>
              <td>Secondary Skill 2</td><td><%= @additional.sskill2%></td>
              <td></td><td></td>
            </tr>
            <tr>
              <td colspan="4" align="center" style="font-size:30px;">BANK DETAILS</td>
            </tr>
            <tr>
              <td>Account Name</td><td><%= @account.accname%></td>
              <td>Account Number</td><td><%= @account.accno%></td>
            </tr>
            <tr>
              <td>Bank</td><td><%= @account.bank%></td>
              <td>Branch</td><td><%= @account.branch%></td>
            </tr>
            <tr>
              <td>IFSC Code</td><td><%= @account.ifsc%></td>
              <td></td><td></td>
            </tr>
            <% if session[:user_type]=='admin'%>
            <tr>
              <td><%= link_to "Edit User", edit_user_path(@user)%></td>
              <td><%= link_to "Generate Pay Slip", new_payslip_path(@user)%></td>
              <td><%= link_to "View Pay Slips", all_payslips_path(@user)%></td>
              <td><%= link_to "Delete User", user_path(@user), method: :delete, data: {confirm: "Are you sure?"}%></td>
            </tr>
            <% end%>
            <% if session[:user_type]=='user'%>
            <tr>
              <td><%= link_to "View Pay Slips", all_payslips_path(@user)%></td>
            </tr>
            <% end%>
        </table>
      </div>
  </body>
</html>